CREATE TABLE IF NOT EXISTS events(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Already comes with an ID(line 25)...make it primary?
    asset_id INTEGER,
    asset_token_id TEXT,
    asset_contract_address TEXT,
    bid_amount TEXT,
    duration TEXT,
    created_date TEXT,
    ending_price TEXT,
    event_type TEXT,
    starting_price TEXT,
    transaction_from_account_address TEXT,
    transaction_from_account_user TEXT,
    transaction_from_account_profile_img_url TEXT,
    transaction_to_account_address TEXT,
    transaction_to_account_user TEXT,
    transaction_to_account_profile_img_url TEXT,
    transaction_timestamp TEXT,
    transaction_hash TEXT,
    payment_token_decimals NUMERIC,
    payment_token_eth_price NUMERIC,
    payment_token_usd_price TEXT,
    total_price TEXT
);

CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text,
    username text UNIQUE,
    profile_img_url text,
    cover_img_url text,
    public_address text NOT NULL,
    config text,
    email text,
    nonce INTEGER,
    bio text,
    website text,
    twitter text,
    instagram text,
    discord_id text,
    youtube text,
    facebook text,
    tiktok text,
    snapchat text,
    discord text,
    creator BOOLEAN
);

CREATE TABLE IF NOT EXISTS usersfollowing(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    follower_id INTEGER REFERENCES users(id),
    followee_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS artworks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    asset_id INTEGER NOT NULL,
    asset_contract_address text NOT NULL,
    asset_token_id text NOT NULL,
    title text,
    description text,
    image_url text,
    image_preview_url text,
    image_thumbnail_url text,
    image_original_url text,
    video_url text,
    creator_username text,
    creator_image_url text,
    creator_address text,
    owner_username text,
    owner_image_url text,
    owner_address text,
    collection_slug text,
    collection_payout_address text,
    collection_name text,
    collection_image_url text,
    status text,
    price_eth text,
    price_usd text,
    is_featured BOOLEAN,
    expiration text,
    schema_name text
);

CREATE TABLE IF NOT EXISTS playlists(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL CHECK (title <> ''),
    description text NOT NULL,
    user_id INTEGER REFERENCES users(id),
    user_address text NOT NULL CHECK (user_address <> ''),
    priority integer NOT NULL
);

CREATE TABLE IF NOT EXISTS playlistsartworks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    playlist_id INTEGER REFERENCES playlists(id),
    artwork_id INTEGER REFERENCES artworks(id),
    priority integer NOT NULL
);

CREATE TABLE IF NOT EXISTS favoritesartworks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id),
    user_address text NOT NULL CHECK (user_address <> ''),
    artwork_id INTEGER REFERENCES artworks(id),
    priority integer NOT NULL
);

CREATE TABLE IF NOT EXISTS exhibitions(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL CHECK (title <> ''),
    description text,
    banner_image_url text,
    image_url text,
    slug text UNIQUE,
    total_supply REAL,
    num_owners INTEGER,
    floor_price REAL,
    total_volume REAL
);

CREATE TABLE IF NOT EXISTS exhibitionsartworks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exhibition_id INTEGER REFERENCES exhibitions(id),
    artwork_id INTEGER REFERENCES artworks(id)
);

-- MOCKS For testing:
-- INSERT INTO Artworks(artist_wallet_address, asset_contract_address, asset_token_id)
--   VALUES('0x904a819e486d4af2653eec8e424599335e2f190e', '0x3b3ee1931dc30c1957379fac9aba94d1c48a5405', '57237');

-- INSERT INTO Artworks(artist_wallet_address, asset_contract_address, asset_token_id)
--   VALUES('0x08dce5266a5cc090ab200322d63ffb5f736db79c', '0x5fd335e64400eabecc9ebe80e3d2fcfb6c001adb', '120');

-- INSERT INTO Artworks(artist_wallet_address, asset_contract_address, asset_token_id)
--   VALUES('0xe052113bd7d7700d623414a0a4585bcae754e9d5', '0xf7b2c72f132a9e1bd00867853a148150bcc6af64', '62200010031');


-- INSERT INTO UsersFollowing(user_name, artist_name, artist_id)
--   VALUES('Diego', '@MetaDrillMinter', 1);
--
-- INSERT INTO playlist(title, description, artist, priority, deliverydate)
--   VALUES('Awesome sunsets', 'NFTs awesome sunsets', 'Diego', '1', '08-07-2021');
--
-- INSERT INTO playlist(title, description, artist, priority, deliverydate)
--   VALUES('Messi GOAT', 'Messi at his prime', 'Diego', '3', '09-07-2021');
--
-- INSERT INTO playlist(title, description, artist, priority, deliverydate)
--   VALUES('Bats and batman', 'Love the animal, hate the hero', 'Carlos', '2', '07-07-2021');
--
--
-- INSERT INTO playlist_artwork(name, priority, playlistid, artist_wallet_address, asset_contract_address, asset_token_id)
--     VALUES('Sunset image3', 1, 1, 'AWA_0123456789x1', 'ACA_0123456789x1', 'ATID_00000003');
--
-- INSERT INTO playlist_artwork(name, priority, playlistid, artist_wallet_address, asset_contract_address, asset_token_id)
--      VALUES('Sunset image2', 2, 1, 'AWA_0123456789x1', 'ACA_0123456789x1', 'ATID_00000002');
--
-- INSERT INTO playlist_artwork(name, priority, playlistid, artist_wallet_address, asset_contract_address, asset_token_id)
--     VALUES('Messi legend dribble', 3, 3, 'AWA_0123456787x0', 'ACA_0123456733x2', 'ATID_00000005');
--
-- INSERT INTO playlist_artwork(name, priority, playlistid, artist_wallet_address, asset_contract_address, asset_token_id)
--      VALUES('Bat on the sky', 2, 2, 'AWA_0123456789x2', 'ACA_0123456789x2', 'ATID_00000002');
--
-- INSERT INTO playlist_artwork(name, priority, playlistid, artist_wallet_address, asset_contract_address, asset_token_id)
--      VALUES('Bat flight', 1, 2, 'AWA_0123456789x5', 'ACA_0123456789x9', 'ATID_00000004');
--
--
-- -- ** artworks **
--
-- INSERT INTO artworks(asset_contract_address, token_id, creator_address)
--         VALUES('0xd23f5e5848b57f03626b7c924a8224975934a4db', 18756, '0xe01b350a05cebfcf27120154fd373b4a2701ac7c')

-- INSERT INTO exhibition(asset_contract_address, token_id, creator_address)
--         VALUES('0xd23f5e5848b57f03626b7c924a8224975934a4db', 18756, '0xe01b350a05cebfcf27120154fd373b4a2701ac7c')

-- INSERT INTO exhibition (id, title, description, artist, priority, deliverydate) VALUES (2, 'exh 2', 'exh desc 2', 'exh 2 artist', 1, '2021-07-24');
-- INSERT INTO exhibition (id, title, description, artist, priority, deliverydate) VALUES (1, 'exh1', 'exh desc 1', 'exh 1 artist', 2, '2021-07-17');
--
-- INSERT INTO exhibition_artworks (id, name, priority, exhibitionid, artist_wallet_address, asset_contract_address, asset_token_id) VALUES (4, 'art duck', 1, 2, '0xf1c5f2c5acc61ecb847967bd0af2ecf1081cad4e', '0x495f947276749ce646f68ac8c248420045cb7b5e', '109357140932249174184232105731133177415490681567806678064024980603877917196289');
-- INSERT INTO exhibition_artworks (id, name, priority, exhibitionid, artist_wallet_address, asset_contract_address, asset_token_id) VALUES (3, 'art bunny', 2, 1, '0xf1c5f2c5acc61ecb847967bd0af2ecf1081cad4e', '0x495f947276749ce646f68ac8c248420045cb7b5e', '109357140932249174184232105731133177415490681567806678064024980598380359057438');